### PR TITLE
Fix language selector visibility

### PR DESCRIPTION
**Pull request by bergice**

### CODE REVIEW

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
The [bambusa mock up](https://projects.invisionapp.com/share/AWO7CJSK426#/screens/331465307_Bambusa_Homepage) displays the language name. This PR doesn't.
image 

The active style is somewhat weird and you only see it when actively clicking on the button.
Screenshot from 2019-07-15 17-43-58

Language men placement on mobile is weird.
image

**Comment by bergice** [comment]
> The [bambusa mock up](https://projects.invisionapp.com/share/AWO7CJSK426#/screens/331465307_Bambusa_Homepage) displays the language name. This PR doesn't.
> image
> 
> The active style is somewhat weird and you only see it when actively clicking on the button.
> Screenshot from 2019-07-15 17-43-58
> 
> Language men placement on mobile is weird.
> image

I've fixed those issues except for the mobile placement as thats the same behavior on watea and starter theme.

**Comment by maxime-rainville** [comment]
@clarkepaul What do we want to do with the language picker on mobile? The [mobile mock up](https://projects.invisionapp.com/share/AWO7CJSK426#/screens/370234429) semi-implies that it should be tucked away in the mobile menu.

But it's not clear.

**Comment by sachajudd** [comment]
I think it makes sense to follow what's in Wātea: image
I don't think the designs considered the language selector.

**Comment by maxime-rainville** [comment]
Actually, I just noticed that the mobile menu doesn't work either.

I'll raise a separated card.

**Comment by sachajudd** [comment]
Think that's covered in #2 @maxime-rainville

**Comment by maxime-rainville** [comment]
You're way ahead of me Sacha ... I'll just be quiet now.

**Review by maxime-rainville — APPROVED** [review]
There's some mobile issue but those will be handled through other jobs.

**Pull request merged**
